### ISSUE TITLE
add `EngineInfo` component

### ISSUE THREAD

**Issue by pbosio** [decentraland/sdk#746] opened 2023-04-27 15:44 UTC
protocol https://github.com/decentraland/protocol/blob/main/proto/decentraland/sdk/components/engine_info.proto
ticks will be count every time `crdtSendToRenderer` is called, which is every time the scene update is performed.

**Comment by pravusjif** [comment] 2023-06-05 16:19
closing as duplicate of https://github.com/decentraland/sdk/issues/737

**Closed as completed by pravusjif** 2023-06-05 16:19 UTC
Labels: renderer
