### ISSUE TITLE
Identify versions of the runtime in the scene.json

### ISSUE THREAD

**Issue by menduz** [decentraland/sdk#507] opened 2022-12-12 15:18 UTC
The `scene.json` should not care about the implementation of the SDK, only about the version of the runtime it runs in.

For that purpose, we should add the `runtimeVersion: string` to the scene.json (manifest) to enable the proper runtime checks and setup.

`runtimeVersion` will use semver in a future, but for now the only enabled value is `"7"`

Already implemented in 
- [x] build-ecs
- [x] kernel

**Comment by nearnshaw** [comment] 2022-12-13 12:37
I believe this one is a duplicate of #471

**Closed** 2022-12-20 18:32 UTC
Labels: sdk7-blocker
